<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>9d76dbaf-6b1c-4037-ac31-bb90618fcd9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button__StyledButton-sc-1l9x0nw-0.jVOJRp.LoginForm__StyledButton-sc-1xs7wb9-11.dDDfYg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd6ffb05-1d8e-4eed-9009-908665cb8196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>orange</value>
      <webElementGuid>b0e6da54-4c91-4b1a-82df-3c55f9448463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>b9268583-bd0e-4402-aef0-29c0409c0418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cf681824-7952-400f-9ac0-723355ddf426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-submit</value>
      <webElementGuid>ae5f3fc0-d7e5-46a2-a479-0f6dfe85700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l9x0nw-0 jVOJRp LoginForm__StyledButton-sc-1xs7wb9-11 dDDfYg</value>
      <webElementGuid>a4dc8916-de2c-437e-b931-83c67b438f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>2f46daef-d821-4cf2-b6da-48c75feb8c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Layout__StyledContainer-kmsxkz-0 dOgPEi&quot;]/main[1]/div[@class=&quot;Login__Container-jowjqu-0 qMqEI&quot;]/div[@class=&quot;Flex__StyledFlex-sc-1gmkxa6-0 iBcdHk&quot;]/form[1]/div[@class=&quot;LoginForm__FooterSection-sc-1xs7wb9-8 eSeKLR&quot;]/button[@class=&quot;Button__StyledButton-sc-1l9x0nw-0 jVOJRp LoginForm__StyledButton-sc-1xs7wb9-11 dDDfYg&quot;]</value>
      <webElementGuid>9c12a44c-4cf3-4490-9c30-ab42571f9268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>c0811b88-644f-40bf-ac36-c02253dbf7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/form/div[2]/button</value>
      <webElementGuid>0af6dbed-07e9-4fdf-bf10-b9ac62f938cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi?'])[1]/following::button[1]</value>
      <webElementGuid>c208cb17-5ab2-4be8-97af-788d01d03258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk Akun Ralali'])[1]/following::button[1]</value>
      <webElementGuid>b172658d-5b7b-4bb6-925d-cfb78196e2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>0ba9995c-102a-4df3-be5d-9fe9b2a5bdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>26874a8f-6836-4836-8f05-ba0b79f05633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>06a608cb-13e4-4987-8ebe-0f9d8ca1c613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
