<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field Password</name>
   <tag></tag>
   <elementGuidId>268aa85d-e52f-45e8-ad2c-51a62e815780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f83ecb0-29de-4881-8497-9e8f71cb16e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18bf9042-c9e3-46d9-a8d3-36c2455cf284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-password</value>
      <webElementGuid>f0a2e2bb-0d50-4882-bc9b-640246792fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c8a61853-86e2-47a0-929b-4864ed9931fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>13px</value>
      <webElementGuid>0fef68f7-a928-47f9-8881-6f064be6cb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>add9453a-a00b-4794-9232-14b445d4b27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480px</value>
      <webElementGuid>7768e9de-d5ce-41b4-bcfe-cb6131fd9a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0dd3c315-00f2-4e10-af16-a0e1909519e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>28047238-06ad-4825-92ed-a8e3cf76a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__Input-jfrtn4-5 cYBHub LoginForm__StyledTextInput-sc-1xs7wb9-10 dvSsMQ</value>
      <webElementGuid>0dfed48e-bacd-44e2-af7b-91835f58356a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Layout__StyledContainer-kmsxkz-0 dOgPEi&quot;]/main[1]/div[@class=&quot;Login__Container-jowjqu-0 qMqEI&quot;]/div[@class=&quot;Flex__StyledFlex-sc-1gmkxa6-0 iBcdHk&quot;]/form[1]/div[@class=&quot;LoginForm__BodySection-sc-1xs7wb9-6 kQOMvq&quot;]/div[@class=&quot;TextInput__FloatLabel-jfrtn4-0 fbAhCp&quot;]/div[@class=&quot;TextInput__Wrapper-jfrtn4-2 gmzAqa&quot;]/div[@class=&quot;TextInput__InputWrapper-jfrtn4-3 kSIKld&quot;]/input[@class=&quot;TextInput__Input-jfrtn4-5 cYBHub LoginForm__StyledTextInput-sc-1xs7wb9-10 dvSsMQ&quot;]</value>
      <webElementGuid>11ca5395-bddb-414c-bb76-cc6a613222fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[2]</value>
      <webElementGuid>4cef3286-32f9-40ce-b86e-960191721f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/form/div/div[2]/div/div/input</value>
      <webElementGuid>52626177-c88f-476f-b7c9-4c4d1aa279e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>3cf30246-43f7-45c1-b46a-d287b083977b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>dc01bb3a-3cbc-469d-b507-690148ea012d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
