<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ConfirmationPassword</name>
   <tag></tag>
   <elementGuidId>b784e518-6555-4ebd-81a3-77d44a5b5a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/main/div[2]/div/form/div[1]/div[5]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6c722fc-8aa1-4ef7-89c2-f9383cbea1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a3efc338-c88f-4433-ad01-6a5808e58d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-password-confirmation</value>
      <webElementGuid>cda3c50a-cbaa-44d4-ab9c-c5bb9c79bc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>00f75de1-9487-4304-8a55-41bdea72efa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Min. 8 - 50 karater terdiri dari huruf kecil besar, angka, dan simbol</value>
      <webElementGuid>777fbde7-5d02-4d74-8de2-a29bd161a32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>13px</value>
      <webElementGuid>6d4d4d58-16bc-47c9-9fc2-1c09e8e84fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>4b6d2bb1-e1ab-40cd-8948-c42a2bc8f9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480px</value>
      <webElementGuid>84eaeba9-d099-44a2-ade3-a50621de7fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6d515974-3455-4132-9a61-fcd9ebbfaabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>742f3903-4cf9-4cfa-a1b7-414428e6d6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__Input-jfrtn4-5 cYBHub RegisterForm__StyledTextInput-sc-1ofjgrt-11 dwUcjN</value>
      <webElementGuid>88529e64-76b2-41d7-b146-3735cb31436e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Layout__StyledContainer-kmsxkz-0 dOgPEi&quot;]/main[1]/div[@class=&quot;Register__Container-sc-1d49mct-0 hhGKLp&quot;]/div[@class=&quot;RegisterForm__RegisterContainer-sc-1ofjgrt-0 eoGkhr&quot;]/form[1]/div[@class=&quot;RegisterForm__BodySection-sc-1ofjgrt-6 kUAsvi&quot;]/div[@class=&quot;TextInput__FloatLabel-jfrtn4-0 fbAhCp&quot;]/div[@class=&quot;TextInput__Wrapper-jfrtn4-2 gmzAqa&quot;]/div[@class=&quot;TextInput__InputWrapper-jfrtn4-3 kSIKld&quot;]/input[@class=&quot;TextInput__Input-jfrtn4-5 cYBHub RegisterForm__StyledTextInput-sc-1ofjgrt-11 dwUcjN&quot;]</value>
      <webElementGuid>df381369-4e69-4064-a96d-80c272c0e0be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[4]</value>
      <webElementGuid>35fa4535-ce2f-4e16-9efb-f748937434ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/form/div/div[5]/div/div/input</value>
      <webElementGuid>aa0c10a4-456f-4a56-8008-3fbd4830358c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>c39f3bc9-f109-4596-89c0-13c462477fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Min. 8 - 50 karater terdiri dari huruf kecil besar, angka, dan simbol']</value>
      <webElementGuid>9a4ec940-0d27-4c62-ad1f-ad762c1e2d81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
