<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>88fb24d3-9501-40f2-bef7-0451708ae844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div/main/div[2]/div/form/div[1]/div[4]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b405ab59-6511-4f28-b881-54ad6eafd136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7c71b181-106c-40bd-b645-322c3a3d4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-password-confirmation</value>
      <webElementGuid>b0dec28d-199d-4b40-891e-5b1039e0305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3efa6549-5fe5-4867-807c-ad5a316856ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>13px</value>
      <webElementGuid>c0dc8f84-cdf7-4949-82e9-df860fba68f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-weight</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>710950c9-63fb-46a6-bb63-5d64b640a64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480px</value>
      <webElementGuid>2ef38fab-d004-413b-b65d-6f958b679c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f3a90c47-8900-40d5-8e09-9e30bd01bb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#333333</value>
      <webElementGuid>5db7844f-e54a-48e8-a8d9-386366717c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__Input-jfrtn4-5 cYBHub RegisterForm__StyledTextInput-sc-1ofjgrt-11 dwUcjN</value>
      <webElementGuid>b61814fa-6fe7-4cbb-9be3-66d5c8923b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Layout__StyledContainer-kmsxkz-0 dOgPEi&quot;]/main[1]/div[@class=&quot;Register__Container-sc-1d49mct-0 hhGKLp&quot;]/div[@class=&quot;RegisterForm__RegisterContainer-sc-1ofjgrt-0 eoGkhr&quot;]/form[1]/div[@class=&quot;RegisterForm__BodySection-sc-1ofjgrt-6 kUAsvi&quot;]/div[@class=&quot;TextInput__FloatLabel-jfrtn4-0 fbAhCp&quot;]/div[@class=&quot;TextInput__Wrapper-jfrtn4-2 gmzAqa&quot;]/div[@class=&quot;TextInput__InputWrapper-jfrtn4-3 kSIKld&quot;]/input[@class=&quot;TextInput__Input-jfrtn4-5 cYBHub RegisterForm__StyledTextInput-sc-1ofjgrt-11 dwUcjN&quot;]</value>
      <webElementGuid>585bfd2e-03ee-48cf-b8f7-93856174737a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name=''])[4]</value>
      <webElementGuid>a9b93eaf-ab60-4f66-a0f3-ae4945ae010e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div/form/div/div[5]/div/div/input</value>
      <webElementGuid>32524182-669c-4a48-b091-f800e70784cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>fe13e2d9-73d6-4918-a19c-0cee27ff4b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>8e1b13a1-6259-4be6-b309-8940cae15aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
